# Generated by Django 3.1.7 on 2022-04-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220425_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
