# Generated by Django 3.1.7 on 2022-04-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userdata_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='gender',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='height',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='weight',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
